"""Fifth Migration

Revision ID: f87b488f1889
Revises: ada337471d5b
Create Date: 2019-02-27 09:25:33.230462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87b488f1889'
down_revision = 'ada337471d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'name')
    op.add_column('pitches', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'published_at')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'author')
    op.add_column('comments', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'published_at')
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
